<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="puzzle" nsURI="http://org.mdse/puzzle" nsPrefix="puzzle">
  <eClassifiers xsi:type="ecore:EClass" name="Puzzle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" lowerBound="1" upperBound="-1"
        eType="#//UnitTest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" eType="#//Inputs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitTest">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expected" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.constructs/model/constructs.ecore#//Literal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failedMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//UnitTestInput" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inputs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.mdse.constructs/model/constructs.ecore#//Variable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitTestInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.constructs/model/constructs.ecore#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overwritingValue" eType="ecore:EClass ../../org.mdse.constructs/model/constructs.ecore#//Literal"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
