<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="game" nsURI="http://org.mdse/game" nsPrefix="game">
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entrypoint" lowerBound="1"
        eType="#//Entrypoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="ecore:EClass ../../org.mdse.puzzle/model/puzzle.ecore#//UnitTest" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStatement" eType="#//GameStatement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.constructs/model/constructs.ecore#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameInputs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStatement" lowerBound="1"
        eType="#//GameStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.puzzle/model/puzzle.ecore#//Inputs" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entrypoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" eType="#//GameInputs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//GameStatement"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
