<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="game" nsURI="http://org.mdse/game" nsPrefix="game">
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="puzzle" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.puzzle/model/puzzle.ecore#//Puzzle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entrypoint" lowerBound="1"
        eType="#//Entrypoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsedStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStatements" upperBound="-1"
        eType="#//UsedStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.puzzle/model/puzzle.ecore#//AllowedStatement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsedInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStatement" eType="#//UsedStatement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="ecore:EClass ../../org.mdse.puzzle/model/puzzle.ecore#//Input"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextInput" eType="#//UsedInput"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entrypoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//UsedInput"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//UsedStatement"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
