<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="game" nsURI="http://org.mdse/game" nsPrefix="game">
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="ecore:EClass ../../org.mdse.puzzle/model/puzzle.ecore#//UnitTest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" eType="ecore:EClass ../../org.mdse.puzzle/model/puzzle.ecore#//Inputs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.mdse.constructs/model/constructs.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnStatement" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.constructs/model/constructs.ecore#//ReturnStatement"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
