/*
 * generated by Xtext 2.25.0
 */
package org.mdse.puzzle.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DSLStandaloneSetup extends DSLStandaloneSetupGenerated {

	public static void doSetup() {
		new DSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
