/*
 * generated by Xtext 2.24.0
 */
package org.mdse.puzzle.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.mdse.puzzle.dsl.DSLRuntimeModule;
import org.mdse.puzzle.dsl.DSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DSLIdeSetup extends DSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DSLRuntimeModule(), new DSLIdeModule()));
	}
	
}
