/*
 * generated by Xtext 2.24.0
 */
package org.mdse.puzzle.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDSLScopeProvider extends DelegatingScopeProvider {
}
