/*
 * generated by Xtext 2.24.0
 */
package org.mdse.puzzle.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://org.mdse/puzzle"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://org.mdse/constructs"));
		return result;
	}
}
